### PR TITLE
Add jenkins healthcheck taskset

### PR DESCRIPTION
**Pull request by jon-funk**
- Adds taskset for healthchecking Jenkins workloads and its rest API in Kubernetes

- Note: there's a bug in the PVC check that has a fix coming in a separate PR which will include changes addressing feedback from yourself & Kyle

### CODE REVIEW

**Review by stewartshea — CHANGES_REQUESTED** [review]
I think the readme is outdated with the tasks that are now removed.

**Review by stewartshea — CHANGES_REQUESTED** [review]
Also, I don't think we want to render anything in command list that needs explicit user names of we can't source them from a secret in the system. Ultimately it renders an unusable command. I'm not sure yet how to solve.this for things like Jenkins and postgres.

**Comment by jon-funk** [comment]
I'm guessing you're referring to:
`${KUBERNETES_DISTRIBUTION_BINARY} exec statefulset/${STATEFULSET_NAME} --context=${CONTEXT} -n ${NAMESPACE} -- curl -s localhost:8080/api/json?pretty=true --user $${JENKINS_SA_USERNAME.key}:$${JENKINS_SA_TOKEN.key}`

Since I'm using the `$${}`  syntax with the key and not the actual value this will result in an ENV variable so `$JENKINS_SA_USERNAME` or  `$JENKINS_SA_TOKEN` in the robot when it's passed in.

In terms of rendering, we could provide something like:
```
export JENKINS_SA_USERNAME=<your jenkins username>
export JENKINS_SA_TOKEN=<your jenkins API token>
```
Thoughts?

**Comment by stewartshea** [comment]
Let's skip it for now. If it requires additional configuration to be
useful, it's not ideal.

If it was something we could easily parse from the system that would be
fine, but as it is, it's not a straight copy paste without additional work.

We can look at how to handle that pattern down the line.

--
Shea Stewart (he/him)
c:647-972-5191 ***@***.***
Book a meeting https://calendly.com/stewartshea

**Review by stewartshea — APPROVED** [review]

**Pull request merged**
