### PR TITLE
Updates deployment health check gen rules to match robot file needs

### PR DESCRIPTION
**Pull request by zacpez**
There was an add and remove of config provided. Just updating the gen rules. :D 

@stewartshea @jon-funk Is there a better value to put here than an empty string?

### CODE REVIEW

**Review by stewartshea — APPROVED** [review]

**Review by stewartshea — COMMENTED** [review]
I don't think we want this set here. The idea is that HOME is pulled in from the runtime environment, so I suspect we shouldn't do this.

**Comment by stewartshea** [comment]
@zacpez is this breaking something on your end? the codebundle, as it stands, runs properly

**Comment by zacpez** [comment]
> @zacpez is this breaking something on your end? the codebundle, as it stands, runs properly
@stewartshea It does run, because ultimately it is pulled from the environment.

My issue is two parts:
1. `DISTRIBUTION` is causing one platform runbook edit bug, as its no longer used. Which was my initial issue to fix. 

2. For `HOME` I noticed it's effecting edit functionality as seen here:
image
I think we can quickly discuss the next solution further, and I am just starting to look at alternate ways to go forward.

**Comment by zacpez** [comment]
@stewartshea I have removed the HOME change for now. It looks to be a unique type of User Variable. I have an idea, more platform focused when we have time for a screen share / call.

**Review by stewartshea — CHANGES_REQUESTED** [review]
Reviewing the robot, the var that we want is KUBERNETES_DISTRIBUTION_BINARY. It still needs to exist, as it is used in the command line for substitution - e.g for users that want to use oc instead of kubectl, this enables the command to switch as such. If removed entirely, it will break the command.

**Review by stewartshea — APPROVED** [review]

**Pull request merged**
